#!/usr/bin/env node
/**
 * Build chrome-extension/content.js from FireWally.user.js
 * Strips Tampermonkey header, injects MV3 GM_* shim + ticketData bridge cache.
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname);
const srcPath = path.join(root, 'FireWally.user.js');
const outPath = path.join(root, 'chrome-extension', 'content.js');

const src = fs.readFileSync(srcPath, 'utf8');
const stripped = src
  .replace(/^\/\/ ==UserScript==[\s\S]*?\/\/ ==\/UserScript==\s*/m, '')
  .trim();

if (!stripped.startsWith('(function')) {
  console.error('Unexpected FireWally.user.js shape — expected IIFE after header');
  process.exit(1);
}

const shim = `/* FireWally Chrome extension content script — generated by _build_extension.js */
/* Do not edit content.js by hand; edit FireWally.user.js and re-run: node _build_extension.js */

(function bootstrapFireWallyExtension() {
  'use strict';

  const __fwStore = Object.create(null);
  let __fwXhrSeq = 0;
  let __fwTicketData = null;

  window.addEventListener('message', (event) => {
    if (event.source !== window) return;
    const msg = event.data;
    if (!msg || msg.source !== 'firewally-bridge' || msg.type !== 'ticketData') return;
    __fwTicketData = msg.data ?? null;
  });

  function __fwRequestTicketData() {
    try { window.postMessage({ source: 'firewally', type: 'requestTicketData' }, '*'); } catch (_) {}
  }
  __fwRequestTicketData();
  setInterval(__fwRequestTicketData, 1500);

  function GM_getValue(key, def) {
    if (Object.prototype.hasOwnProperty.call(__fwStore, key)) return __fwStore[key];
    return def;
  }

  function GM_setValue(key, value) {
    __fwStore[key] = value;
    try { chrome.storage.local.set({ [key]: value }); } catch (_) {}
  }

  function GM_xmlhttpRequest(details) {
    const id = 'xhr_' + (++__fwXhrSeq) + '_' + Date.now();
    const payload = {
      type: 'fw_xhr',
      id,
      method: details.method || 'GET',
      url: details.url,
      headers: details.headers || {},
      data: details.data,
      timeout: details.timeout || 120000,
    };

    chrome.runtime.sendMessage(payload, (resp) => {
      if (chrome.runtime.lastError) {
        try { details.onerror?.(new Error(chrome.runtime.lastError.message)); } catch (_) {}
        return;
      }
      if (!resp || resp.ok === false) {
        if (resp && resp.timeout) {
          try { details.ontimeout?.(); } catch (_) {}
        } else {
          try { details.onerror?.(resp); } catch (_) {}
        }
        return;
      }
      try {
        details.onload?.({
          status: resp.status,
          responseText: resp.responseText || '',
          responseHeaders: resp.responseHeaders || '',
        });
      } catch (_) {}
    });

    return {
      abort() {
        try { chrome.runtime.sendMessage({ type: 'fw_xhr_abort', id }); } catch (_) {}
      },
    };
  }

  // Userscript expects sync unsafeWindow.ticketData — feed a cache updated by page-bridge.js
  const unsafeWindow = {
    get ticketData() { return __fwTicketData; },
  };

  async function __fwHydrate() {
    try {
      const all = await chrome.storage.local.get(null);
      Object.assign(__fwStore, all || {});
    } catch (e) {
      console.warn('[FireWally] storage hydrate failed', e);
    }
  }

  __fwHydrate().then(() => {
    try {
      try { chrome.runtime.sendMessage({ type: 'fw_content_ready' }); } catch (_) {}
/* ==== begin FireWally app (from FireWally.user.js) ==== */
`;

const footer = `
/* ==== end FireWally app ==== */
    } catch (e) {
      console.error('[FireWally] failed to start', e);
    }
  });
})();
`;

// Patch readTicketData to prefer bridge cache (unsafeWindow getter) — already works via unsafeWindow shim.
// Soft-label version in UI so it's obvious this is the extension build.
let app = stripped;
app = app.replace(
  /const VERSION = '([^']+)';/,
  (m, v) => `const VERSION = '${v}-ext';`
);

const out = shim + '\n' + app + '\n' + footer;
fs.writeFileSync(outPath, out, 'utf8');
console.log('Wrote', outPath, '(' + out.length + ' bytes)');
